PaginaWeb/BEAT/urls.py
from ast import arg
from urllib import request
from BEAT import views
from django.urls import path
app_name='BEAT'
urlpatterns = [
    path('index/',views.index,name="index"),
    path('music/',views.songs,name="musica"),
    path('ingreso/',views.ingreso,name="ingreso"),
    path('registro/',views.registro,name="registro"),
    path("hacerRegistro/",views.hacerRegistro,name="hacerRegistro"),
    path("logIn/",views.LogIn,name="logIn"),
    path("add/",views.add,name="add"),
    path("addNew/",views.addNew,name="addNew"),
    path("errorIn/",views.errorIngreso,name="errorIn"),
    path("",views.firstOpen,name="fOpen")
]

PaginaWeb/PaginaWeb/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('BEAT/', include('BEAT.urls')),
]

PaginaWeb/BEAT/models.py
from django.db import models
from unittest.util import _MAX_LENGTH

# Create your models here.
class usuario(models.Model):
    nombre=models.CharField(max_length=50)
    password=models.CharField(max_length=30)
    registro=models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.nombre

class cancion(models.Model):
    name=models.CharField(max_length=50)
    imagenSec=models.CharField(max_length=100)
    audioSec=models.CharField(max_length=100)
    Prim=models.CharField(max_length=100)

class state(models.Model):
    status=models.CharField(max_length=2)
    pkU=models.IntegerField()

PaginaWeb/BEAT/views.py
from email.mime import audio
from getpass import getuser
from http.client import HTTPResponse
from django.shortcuts import render
from BEAT.models import usuario,cancion,state
# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone as Tz
from django.urls import reverse
import os
def firstOpen(request):
    state.objects.all().delete()
    return HttpResponseRedirect(reverse("BEAT:index"))

def index(request):
    try:
        stat=state.objects.all()[0]
        estado=stat.status
        identificador=stat.pkU
    except:
        estado="F"
        identificador=0
    names=usuario.objects.all()[identificador].nombre
    largo=len(cancion.objects.all())-1
    imagen={}
    user=getuser()
    i=cancion.objects.all()[0]
    imagen=i.Prim.replace("C:","/static/C%3A")+user+i.imagenSec.replace("0.png","")
    return render(request,"BEAT\index.html",{'imagenes':imagen,'estado':estado,'logeado':names,'largo':largo})
def songs(request):
    try:
        stat=state.objects.all()[0]
        estado=stat.status
        identificador=stat.pkU
    except:
        estado="F"
        identificador=0
    names=usuario.objects.all()[identificador].nombre
    imagen=""
    song=""
    user=getuser()
    i=cancion.objects.all()[0]
    imagen=i.Prim.replace("C:","/static/C%3A")+user+i.imagenSec.replace("0.png","")
    song=i.Prim.replace("C:","/static/C%3A")+user+i.audioSec.replace("0.mp3","")

    return render(request,"BEAT\songsPage.html",{'imagenes':imagen,'canciones':song,'largo':
    len(cancion.objects.all()),'logeado':names,'estado':estado})

def registro(request):
    return render(request,"BEAT\sigIn.html")

def ingreso(request):
    return render(request,"BEAT\ingreso.html",{'sts':False})

def add(request):
    return render(request,"BEAT/add.html")

def addNew(request):
    try:
        names=request.POST['nombre']
        track=request.POST['audios']
        icon=request.POST['imagenes']
    except:
        return HttpResponse("Error")
    else:
        strack=str(track)
        simage=str(icon)
        user=getuser()
        ruta=f'C:/Users/{user}/Downloads/'
        Sruta=f'C:/Users/{user}/Documents/miPaginaWeb/PaginaWeb/BEAT/templates/BEAT/static'
        os.rename(ruta+strack,Sruta+'/cancion'+str(len(cancion.objects.all()))+'.mp3')
        os.rename(ruta+simage,Sruta+'/imagen'+str(len(cancion.objects.all()))+'.png')
        rutaSong='/Documents/miPaginaWeb/PaginaWeb/BEAT/templates/BEAT/static'+'/cancion'+str(len(cancion.objects.all()))+'.mp3'
        rutaIcon='/Documents/miPaginaWeb/PaginaWeb/BEAT/templates/BEAT/static'+'/imagen'+str(len(cancion.objects.all()))+'.png'
        newSong=cancion(name=names,Prim='C:/Users/',audioSec=rutaSong,imagenSec=rutaIcon)
        newSong.save()
        return HttpResponseRedirect(reverse("BEAT:musica"))

def hacerRegistro(request):
    try:
        name=request.POST['user']
        passw=request.POST['password']
        register=str(Tz.now()).replace("+00:00","")
    except:
        return HttpResponse("Error")
    else:
        newUser=usuario(
            nombre=name,
            password=passw,
            registro=register
        )
        newUser.save()
        return HttpResponseRedirect(reverse("BEAT:index"))

def LogIn(request):
    try:
        name=request.POST['user']
        passw=request.POST['password']
    except:
        return HttpResponse("Error")
    else:
        for i in usuario.objects.all():
            if(i.nombre==name and i.password==passw):
                newState=state(status="",pkU=i.pk-1)
                newState.save()
                return HttpResponseRedirect(reverse("BEAT:index"))
        newState=state(status="T",pkU=0)
        newState.save()
        return HttpResponseRedirect(reverse("BEAT:errorIn"))

def errorIngreso(request):
    state.objects.all().delete()
    return render(request,"BEAT\ingreso.html",{'sts':True})

PaginaWeb/BEAT/templates/BEAT/add.html
{%load static%}
<!DOCTYPE html>
<!-- INICIO DEL DOCUMENTO HTML-->
<html lang="en">
<head>
	<!-- EN ESTA ZONA AÑADIMOS CARACTERES ESPECIALES DEL IDIOMA ESPAÑOL-->
	<meta charset="utf-8">
	<!-- TITULO DE LA PAGINA-->
	<title>About Us</title>
	<!-- ACA ANCLAMOS LA HOJA DE ESTILOS DE CSS-->
	<link rel="stylesheet" href={%static "/add.css"%}>
</head>
<!-- INICIO DEL CUERPO-->
<body>
	<header>
		<h1 id="NuevasCanciones">New songs</h1>
		<ol id="botones">
			<a href="../music/"  id="songs"><button id="button--songs"> Canciones</button></a>
			<a href="../index/" id="Principal"><button id="button--volver">Pagina principal</button></a>
		</ol>
	</header>
	<main>
        <form action="{% url 'BEAT:addNew' %}" id="newSong" method="post">
			{%csrf_token%}
            <input type="text" name="nombre" id="NAME" placeholder="Nombre de la cancion">
            <li>
            <label for="audio" class="labels" id="label--audio">Audio</label>
            <input type="file" id="audio" name="audios" accept="audio/*" class="files">
            <label for="image" class="labels" id="label--imagen">Imagen</label>
            <input type="file" id="image" name="imagenes" accept="image/*" class="files">
        </li>
            <input type="submit" valor="enviar" id="addSong">
        </form>
	</main>
	<footer>

	</footer>
</body>
<script src={%static "/add.js"%} type="text/javascript"></script>
</html>

PaginaWeb/BEAT/templates/BEAT/index.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Portada</title>
	<link rel="stylesheet" href={%static "/estio.css"%}>
</head>
<body>
	<header>
		<h1 id="BEAT">8-BEAT</h1>
		<ol id="botones">
			<a href="../music/" id="Songs"><button id="button--Canciones">Canciones</button></a>
			{%if estado %}
			<a href="../ingreso/" id="US"><button id="button--US">Ingresar</button></a>
			{%else%}
            <a href="../add/" id="add_new"><button id="button--add_song">Añadir cancion</button></a>
			<h3 id="button--US">usuario: {{logeado}}</h3>
			{%endif%}
		</ol>
	</header>
	<main>
		<h2 id="novedad">Novedades</h2>

	</main>
</body>
</html>

PaginaWeb/BEAT/templates/BEAT/ingreso.html
{%load static%}
<!DOCTYPE html>
<!-- INICIO DEL DOCUMENTO HTML-->
<html lang="en">
<head>
	<!-- EN ESTA ZONA AÑADIMOS CARACTERES ESPECIALES DEL IDIOMA ESPAÑOL-->
	<meta charset="utf-8">
	<!-- TITULO DE LA PAGINA-->
	<title>About Us</title>
	<!-- ACA ANCLAMOS LA HOJA DE ESTILOS DE CSS-->
	<link rel="stylesheet" href={%static "/ingreso.css"%}>
</head>
<!-- INICIO DEL CUERPO-->
<body>
	<header>
		<h1 id="About_us">Ingresar</h1>
		<ol id="botones">
			<a href="../music/" id="songs"><button id="button--songs"> Canciones</button></a>
			<a href="../index/" id="Principal"><button id="button--volver">Pagina principal</button></a>
		</ol>
	</header>
	<main>
		<form id="formulario_ingreso"action="{% url 'BEAT:logIn' %}" method="post">
			{%csrf_token%}
			<input type="text" id="usuario" name="user" placeholder="usuario">
			<input type="text" id="password" name="password" placeholder="contraseña">
			<input type="submit" valor="enviar" id="sig_in--button">
		</form>
		{% if sts %}
		    <h2 id="comprobacion">Lo sentimos, el usuario o contraseña son incorrectos</h2>
		{% endif %}
		<ol id="sig_in">
			<h2 id="sig_in--text">¿No tienes una cuenta?, intenta</h2>
			<a href="../registro/"><button id="sig_in--button"> Crear un usuario nuevo</button></a>
		</ol>
	</main>
	<footer>

	</footer>
</body>
</html>

PaginaWeb/BEAT/templates/BEAT/sigIn.html
{%load static%}
<!DOCTYPE html>
<!-- INICIO DEL DOCUMENTO HTML-->
<html lang="en">
<head>
	<!-- EN ESTA ZONA AÑADIMOS CARACTERES ESPECIALES DEL IDIOMA ESPAÑOL-->
	<meta charset="utf-8">
	<!-- TITULO DE LA PAGINA-->
	<title>About Us</title>
	<!-- ACA ANCLAMOS LA HOJA DE ESTILOS DE CSS-->
	<link rel="stylesheet" href={%static "/sigIn.css"%}>
</head>
<!-- INICIO DEL CUERPO-->
<body>
	<header>
        <h1 id="sig_in">Nuevo Usuario</h1>
        <ol id="botones">
			<a href="../music/" id="songs"><button id="button--songs"> Canciones</button></a>
			<a href="../index/ " id="Principal"><button id="button--volver">Pagina principal</button></a>
        </ol>
	</header>
	<main>
        <form action="{% url 'BEAT:hacerRegistro' %}" id="sig_in--form" method="post">
			{% csrf_token %}
            <input type="text" id="usuario" name="user" placeholder="usuario">
			<input type="text" id="password" name="password" placeholder="contraseña">
			<input type="submit" valor="enviar" id="crear_usuario">
        </form>
	</main>
	<footer>
	</footer>
</body>
</html>

PaginaWeb/BEAT/templates/BEAT/songsPage.html
{%load static%}
<!DOCTYPE html>
<!-- INICIO DEL DOCUMENTO HTML-->
<html lang="en">
<head>
	<!-- EN ESTA ZONA AÑADIMOS CARACTERES ESPECIALES DEL IDIOMA ESPAÑOL-->
	<meta charset="utf-8">
	<!-- TITULO DE LA PAGINA-->
	<title>Canciones</title>
	<!-- ACA ANCLAMOS LA HOJA DE ESTILOS DE CSS-->
	<link rel="stylesheet" href={%static "/estilosPage.css"%}>
    <link rel="shortcut icon" href="#">
</head>
<!-- INICIO DEL CUERPO-->
<body>
    <script>
        let img="{{imagenes}}"
        let aud="{{canciones}}"
        let ancho="{{largo}}"
    </script>
    <header>
		<h1 id="songs">Canciones</h1>
		<ol id="botones">
			<a href="../index/ " id="Principal"><button id="button--volver">Pagina principal</button></a>
			{%if estado %}
			<a href="../ingreso/" id="US"><button id="button--US">Ingresar</button></a>
			{%else%}
            <a href="../add/" id="add_new"><button id="button--add_song">Añadir cancion</button></a>
			<h3 id="button--US">usuario: {{logeado}}</h3>
			{%endif%}
		</ol>
	</header> 
    <nav>
        <button id="anteriorPagina" onclick="backBar()">Pagina anterior</button>
        <ol>
            <img id="disk1" height="100" width="100" src="#" onclick="start(1+(barra*5))"/>
            <img id="disk2" height="100" width="100" src="#" onclick="start(2+(barra*5))"/>
            <img id="disk3" height="100" width="100" src="#" onclick="start(3+(barra*5))"/>
            <img id="disk4" height="100" width="100" src="#" onclick="start(4+(barra*5))"/>
            <img id="disk5" height="100" width="100" src="#" onclick="start(5+(barra*5))"/>
            <audio id="song" >
                <source  src="#"type="audio/mpeg" id="source">
            </audio>
        </ol>
        <button id="siguientePagina" onclick="sigBar()">Siguiente pagina</button>
    </nav>
    <main>
        <button id="antes" onclick="actual-=1;nextBack(actual,0)">Cancion Anterior</button>
        <img id="Centro" height="200" width="200" src="#"/>
        <button id="siguiente" onclick="actual+=1;nextBack(actual,1)">Siguiente Cancion</button>
</main>
    <footer>
        <button id="reproduccion" onclick="reprod()">Reproducir/pausar</button>
    </footer>
</body>
<script> 
    let barra=0
    const atras=document.getElementById('antes')
    const sig=document.getElementById('siguiente')
    let stat=false
    let centro=document.getElementById('Centro')
    let recurso=document.getElementById('source')
    let cancion=document.getElementById('song')
    let rep=document.getElementById('reproduccion')
    let actual
    let i=0
    while(i<5){
        document.getElementById('disk'+(i+1)).src=img+i+".png"
        i+=1
    }
    centro.src=document.getElementById('disk1').src=img+"0.png"
    function sigBar(){
        barra+=1
        if(barra>(parseInt(ancho/5))){
             barra=0
        }
        cambioNav()
    }
    function backBar(){
        barra-=1
        if(barra<=-1){
             barra=(parseInt(ancho/5))
        }
        cambioNav()
    }
    function cambioNav(){
        i=0
        while(i<5){
            if((i+barra*5)>=ancho){
                document.getElementById('disk'+(i+1)).src=img+"NAN.png"
            }else{
            document.getElementById('disk'+(i+1)).src=img+((barra*5)+i)+".png"
            }
            i+=1
        }
    }
    function reprod(){
        if(stat){
            cancion.pause()
            stat=false
        }else{
            cancion.play()
            stat=true
        }
    }
    function nextBack(ids,sta){
        if(sta==1){
            if(ids>5+barra*5){
                ids=1+barra*5
                actual=1+barra*5
            }  
        }else{
            if(ids<1+barra*5){
                ids=5+barra*5
                actual=5+barra*5
            }
        }
        cancion.pause()
        centro.src=document.getElementById('disk'+(ids-barra*5)).src
        recurso.src=aud+((ids)-1)+".mp3"
        cancion=document.getElementById('song')
        cancion.load(recurso.src,function(response){
            console.log(response)
        })
        console.log(ids)
        cancion.play()
        stat=true
    }
    function start(ids){
        cancion.pause()
        stat=false
        centro.src=document.getElementById('disk'+(ids-barra*5)).src
        recurso.src=aud+(ids-1)+".mp3"
        cancion=document.getElementById('song')
        cancion.load(recurso.src,function(response){
            console.log(response)
        })
        actual=ids
        cancion.play()
        stat=true
    }
</script>
</html>